name: Audit Workflow
on: push

jobs:
  run-audit:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: apply env vars
        uses: zowe-actions/global-configurations@main

      - name: fetch env vars
        run: echo $DEFAULT_NODE_VERSION
      
      # - name: Setup Node
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: '14'

      # - name: Install
      #   run: npm install --no-audit

      # - name: Audit
      #   run: npm audit
