name: Audit Workflow
on: push

jobs:
  run-audit:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      
      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: install
        run: npm install --no-audit

      - name: audit
        run: npm run audit
