name: Lint Workflow
on: pull_request

jobs:
  run-lint:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install
        run: npm install --no-audit

      - name: Lint
        run: npm run lint

