name: lint Workflow
on: push

jobs:
  run-lint:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      
      - name: setup node
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: run lint
        run: npm run lint

